name: Build flask webapp Docker image

on:
    push:  
     branches:
        - main    
jobs:
   build_image:
     name: main
     runs-on: ubuntu-latest  
     steps:    
       -
         name: Get commit ID
         id: commit
         uses: prompt/actions-commit-hash@v3
       - 
         name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       -
         name: Build and push
         uses: docker/build-push-action@v4
         with:
           file: ./web_app/Dockerfile
           push: true
           tags: dockerprojectuser/flask_route_webapp:${{ steps.commit.outputs.short }}